### ISSUE TITLE
Support recurring payments

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-braintree#12]
Requested [here on the forums](https://easydigitaldownloads.com/forums/topic/presales-braintree-payments-and-recurring-payments-extension/) and [here in support](https://secure.helpscout.net/conversation/253927148/0/).

**Comment by pippinsplugins** [comment]
This will be done in Recurring Payments itself and is logged already so closing this one. See https://github.com/easydigitaldownloads/edd-recurring/issues/93
