### ISSUE TITLE
Charging in the wrong Currency

### ISSUE THREAD

**Issue by RuiSantosdotme** [easydigitaldownloads/edd-braintree#3]
Hi,
I was testing the EDD Braintree extension on my website. Here's the problem.
I live in Portugal, so in Braintreegateway.com my default currency is EUR.
Since my audience is mainly from the USA, all my products have a USD price.

After inserting the API keys and IDs of braintree on EDD.
I tested the payment with a real credit card that I own. Then I tried to order a product (just like a customer would do) everything went fine and I saw that I was going to be charged $2.

When I finish the order and I went to braintree I saw 2EUR there.
And on my credit card statement I was charged 2EUR when in reality and should only be carged 2USD (1,79EUR)

I imagine that people that are using this extension are facing the same problem, If their default currency on EDD is different from braintree's.

I guess that your code on EDD braintree extension can't overwrite braintree's default currency at this moment.
Any thoughts? 
Thank you for your great work and If I see everything working smoothly I'm happy to pay for the license key to support your work. 

P.S. I've been using EDD with Paypal without any problem, but I want to add the credit card option.

**Comment by pippinsplugins** [comment]
Hi @RuiSantosdotme, since this is a support request, I'll have to ask that you open a support ticket and provide a copy of your license key: https://easydigitaldownloads.com/support.
